### ISSUE TITLE
传输大文件会发生超时

### ISSUE THREAD

**Issue by Leadrive** [fengdingfeilong/filetrans#2]
传输超过1G的文件时，
func (sc *tcpSCBase) checkConnection
这里会超时，由于时间的更新是在Read中，传输Data时，这个时间没更新，
带来两个问题：
1、Server端会close socket
2、没检测到连接关闭了，文件句柄没正确关闭，导致文件没写进去

**Comment by Leadrive** [comment]
server端也会调用handleConn
在这里做checkConnection
但在Write中，没更新时间

**Comment by Leadrive** [comment]
目前只在正常传输完毕时，对文件做Close
如果出现异常时，文件就没Close，内容会丢失

**Comment by Leadrive** [comment]
还有个bug，如果文件下载中断，重新下载时，filedata.go中
if offset == 0 { //the first offset
		//fmt.Println("first packet received")
		f, err := os.OpenFile(spath, os.O_WRONLY|os.O_CREATE, os.ModeAppend|os.ModePerm)
条件不符合，没打开文件

**Comment by fengdingfeilong** [comment]
还有个bug，如果文件下载中断，重新下载时，filedata.go中
if offset == 0 { //the first offset
//fmt.Println("first packet received")
f, err := os.OpenFile(spath, os.O_WRONLY|os.O_CREATE, os.ModeAppend|os.ModePerm)
条件不符合，没打开文件

--------------》
文件只在收到第一个包时创建并打开，收到最后一个包时关闭。offset为0时，文件已经打开，断线重连只需要继续往里面写数据就行了

**Comment by fengdingfeilong** [comment]
> 还有个bug，如果文件下载中断，重新下载时，filedata.go中
> if offset == 0 { //the first offset
> //fmt.Println("first packet received")
> f, err := os.OpenFile(spath, os.O_WRONLY|os.O_CREATE, os.ModeAppend|os.ModePerm)
> 条件不符合，没打开文件

文件只在收到第一个包时创建并打开，收到最后一个包时关闭。offset为0时，文件已经打开，断线重连只需要继续往里面写数据就行了

**Comment by fengdingfeilong** [comment]
> 传输超过1G的文件时，
> func (sc *tcpSCBase) checkConnection
> 这里会超时，由于时间的更新是在Read中，传输Data时，这个时间没更新，
> 带来两个问题：
> 1、Server端会close socket
> 2、没检测到连接关闭了，文件句柄没正确关闭，导致文件没写进去

同步处理消息包，read被block住了
